[package]
name = "milk"
version = "0.1.0"
authors = ["John Weachock <jweachock@gmail.com>"]
edition = "2018"

[dependencies]
exitfailure = "0.5.1"
failure = "0.1.5"
git2 = "0.7"
structopt = "0.2.14"

[[bin]]
name = "milk"
path = "src/main.rs"

[[bin]]
name = "milk-init"
path = "src/init.rs"
